/**
 * Writes design/wireframes/tokens.css from the packages/ui tokens.
 * Run from the repo root: `pnpm --filter @sds/ui tokens:css`
 * (or `node packages/ui/scripts/generate-tokens-css.ts`; Node 24 strips the types).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { DEVICES, resolveTokens, toCssVariables } from '../src/index.ts';

const target = fileURLToPath(new URL('../../../design/wireframes/tokens.css', import.meta.url));

const parts = [
  '/* GENERATED by packages/ui/scripts/generate-tokens-css.ts. Do not edit by hand. */',
  '/* Regenerate: pnpm --filter @sds/ui tokens:css */',
  '',
  '/* Default (iPad) so a page without data-device still renders. */',
  toCssVariables(resolveTokens('ipad')),
  ...DEVICES.map((device) => toCssVariables(resolveTokens(device), `[data-device="${device}"]`)),
];

writeFileSync(target, parts.join('\n'));
console.log(`wrote ${target}`);
