/**
 * Writes the token CSS from the packages/ui tokens, to two places:
 * - design/wireframes/tokens.css (the mockups);
 * - packages/ui/src/tokens.css (what the apps import, next to glass.css).
 * Run from the repo root: `pnpm --filter @sds/ui tokens:css`
 * (or `node packages/ui/scripts/generate-tokens-css.ts`; Node 24 strips the types).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { cssVariableEntries, DEVICES, resolveTokens, toCssVariables } from '../src/index.ts';

const targets = [
  fileURLToPath(new URL('../../../design/wireframes/tokens.css', import.meta.url)),
  fileURLToPath(new URL('../src/tokens.css', import.meta.url)),
];

/** The dark theme only restates what differs from the light one (iPad values; devices share colours). */
function darkBlock(): string {
  const light = new Map(cssVariableEntries(resolveTokens('ipad')));
  const lines = cssVariableEntries(resolveTokens('ipad', {}, 'dark'))
    .filter(([name, value]) => light.get(name) !== value)
    .map(([name, value]) => `  ${name}: ${value};`);
  return `[data-theme="dark"] {\n${lines.join('\n')}\n}\n`;
}

const parts = [
  '/* GENERATED by packages/ui/scripts/generate-tokens-css.ts. Do not edit by hand. */',
  '/* Regenerate: pnpm --filter @sds/ui tokens:css */',
  '',
  '/* Default (iPad) so a page without data-device still renders. */',
  toCssVariables(resolveTokens('ipad')),
  ...DEVICES.map((device) => toCssVariables(resolveTokens(device), `[data-device="${device}"]`)),
  '/* Dark theme (kitchen display): set data-theme="dark" on the element that should be dark. */',
  darkBlock(),
];

for (const target of targets) {
  writeFileSync(target, parts.join('\n'));
  console.log(`wrote ${target}`);
}
